### ISSUE TITLE
Unable to find version `v2`

### ISSUE THREAD

**Issue by blendthink** [kuhnroyal/flutter-fvm-config-action#23]
@kuhnroyal 
Thank you for providing such a wonderful tool. ❤️ 

Unable to resolve action `kuhnroyal/flutter-fvm-config-action@v2`, unable to find version `v2`.

Could you please push the v2 tag?

Log:
https://github.com/blendthink/temp/actions/runs/6902193487

**Comment by kuhnroyal** [comment]
Done, sorry!
