### ISSUE TITLE
v2.1 no longer runs properly and errors out

### ISSUE THREAD

**Issue by zeshuaro** [kuhnroyal/flutter-fvm-config-action#29]
Like the title describes, v2.1 (and latest v2) no longer runs. See [here](https://github.com/zeshuaro/firestore_cache/actions/runs/10542835291) for sample GitHub Actions logs and below for the error:
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/firestore_cache/firestore_cache/config-action'. Did you forget to run actions/checkout before running your local action?
```

While the error suggests I might not have run `actions/checkout`, I haven't made any changes to my workflow and would still have run checkout.

**Comment by 3lVv0w** [comment]
got the same issues

**Comment by twogood** [comment]
As a workaround I changed my workflows to use version 2.0

![image](https://github.com/user-attachments/assets/59c9d881-243a-4cb5-873d-c4c8f78511bb)

**Comment by kuhnroyal** [comment]
Ouch, don't understand yet, why this works in tests but not in other repos.

**Comment by kuhnroyal** [comment]
I reverted the `v2` tag for now to point to `v2.0`.

**Comment by kuhnroyal** [comment]
This should work now on v2.2, please test and let me know if anything else fails.
