### ISSUE TITLE
Flutter Flock

### ISSUE THREAD

**Issue by xni06** [kuhnroyal/flutter-fvm-config-action#34]
[Flock](https://getflocked.dev) uses FVM to pull down the relevant version of Flutter. To achieve this it relies on the following `.fvmrc` configuration:

```json
{
  "flutter": "master",
  "flutterUrl": "https://github.com/Flutter-Foundation/flutter.git"
}
```

Is it possible to modify how the `.fvmrc` is parsed so that it takes into account the `flutterUrl`?

**Comment by xni06** [comment]
Extracting the URL isn't the problem - getting `subosito/flutter-action` is the problem.

**Comment by kuhnroyal** [comment]
You can reopen the ticket if the flutter-action wants to support this madness.
